# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'created_time'), 'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u70ba\u5c0e\u822a'),
        ),
    ]
