# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190629_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ower',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '\u4e0a\u7ebf'), (2, '\u8349\u7a3f'), (3, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
