# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190629_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '\u4e0a\u7ebf'), (3, '\u5220\u9664')], default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
