# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190630_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.Tags', verbose_name='\u6807\u7b7e'),
        ),
    ]
